CREATE TABLE IF NOT EXISTS /*_*/wbs_evaluations (
	id INT(11) NOT NULL AUTO_INCREMENT,
	timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	session_id VARBINARY(256) NOT NULL DEFAULT 0,
	entity VARBINARY(2568) NOT NULL DEFAULT 0,
	properties VARBINARY(2048) NOT NULL DEFAULT 0,
	suggestions VARBINARY(2048)NOT NULL DEFAULT 0,
	missing VARBINARY(2048) NULL DEFAULT NULL,
  opinion VARBINARY(2048) NULL DEFAULT NULL,
	overall VARBINARY(5) NULL DEFAULT NULL,
	PRIMARY KEY (id)
) /*$wgDBTableOptions*/;
