CREATE TABLE IF NOT EXISTS /*_*/wbs_evaluations (
	id INT unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT,
	timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	session_id VARBINARY(256) NOT NULL,
	entity VARBINARY(2568) NOT NULL,
	properties VARBINARY(2048) NOT NULL,
	suggestions VARBINARY(2048) NOT NULL,
	missing VARBINARY(2048) NULL,
	opinion VARBINARY(2048) NULL,
	overall VARBINARY(5) NULL
) /*$wgDBTableOptions*/;
